os: linux

addons:
  apt:
    packages:
      - build-essential
      - python3-dev

cache:
    pip: true

language: "python"
python:
  - "3.8"
  - "3.9"

install:
  - pip install -r dev-requirements.txt

before_script:
  - python3 setup.py build_ext --inplace

script:
  - pytest --cov=app tests

after_success:
  - codecov -t f99ed916-43ce-48fd-8934-ebfdbab9b596