[tool.poetry]
name = "Serengeti"
version = "0.2.2"
description = "Secure Proxy used to verify user positions"
authors = ["Angelo Cutaia <angeloxx92@hotmail.it>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "0.7.0"
aiologger = "0.6.1"
uvicorn = {extras = ["standard"], version = "0.14.0"}
orjson = "3.5.3"
python-jose = {extras = ["cryptography"], version = "3.3.0"}
gunicorn = "20.1.0"
aiohttp = {extras = ["speedups"], version = "3.7.4.post0"}
fastuuid = "0.6.0"
fastapi = "0.65.2"

[tool.poetry.dev-dependencies]
flake8 = "3.9.2"
black = "21.5b2"
Cython = "0.29.23"
aioresponses = "0.7.2"
codecov = "2.1.11"
pytest = "6.2.4"
pytest-asyncio = "0.15.1"
pytest-cov = "2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
