name: Test
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install wheel
          pip install poetry
          poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false
          PIP_DEFAULT_TIMEOUT: 300
      - name: Build Cython
        run: |
          python setup.py build_ext --inplace
      - name: Lint with flake8
        run: |
          flake8 app/
      - name: Check Black format
        run: |
          black app tests --check
      - name: Test with pytest
        run: |
           pytest --cov=app --cov-report=xml tests
      - name: Upload coverage
        uses: codecov/codecov-action@v1
